global using Neura.Core.Abstractions;
global using Neura.Core.Contracts.Course;
global using Neura.Core.Entities;
global using Neura.Core.Errors;
global using Neura.Repository.Persistence;
global using HashidsNet;
global using Mapster;
global using Microsoft.EntityFrameworkCore;
global using Neura.Core.Services;
